ministryofjustice/cloud-platform-terraform-rds-instance

README.md, example/main.tf, main.tf, output.tf, variables.tf
connects to ministryofjustice/cloud-platform#303
**WHAT** 
- Remove database port variable from README.md, variables.tf and main.tf
- Add RDS ID output 
**WHY**
- By removing database port, Terraform will use the standard depending on the database chosen. e.g. Postgres - 5432.
- Users want to output the RDS instance ID from the module and are unable to in the current module.
=> Fix module for users

README.md, main.tf, variables.tf
- Prefix the default db name with `"db"` so that it always begins with a letter (PostgreSQL limitation)
- `vpc_security_group_ids` was wrongly given the security group name
- Introduce `snapshot_identifier` to allow creating a new instance from a snapshot.
=> Fixes and snapshot_identifier

README.md, output.tf
connects to ministryofjustice/cloud-platform#462
**WHAT**
- Add RDS instance address and port output
- Amend documentation to show new outputs available 
**WHY**
Prison Visits Booking team are looking to migrate their Ruby application onto the new cloud platform. The team would like a new output available on the module that has the host name without the port.
=> Add RDS Instance address and port as an output

main.tf
Terraform 0.11.10 complains about it
=> Remove leading slash from backend config

main.tf
For postgres the first character must be a letter.
https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html
=> Prefix master username with alphanumerics

variables.tf
Since `auto_minor_version_upgrade` is enabled (default) the instances will receive automatic patches and specifying a
minor version here causes terraform to want to downgrade when an automatic update is pushed to the db instances.
=> Specify only major version for postgres 10

main.tf
**Why**
Without this, changes like storage size only run in the maintenance window, default Monday
=> apply changes immediately

README.md, example/main.tf, example/rds.tf, main.tf, variables.tf
- example/main.tf became example/main.tf AND example/rds.tf
- took the providers out of the module, adding default `aws.london` and `aws.ireland`
- Updated Readme
=> split main and rds example, took providers out of module

README.md
* Mention the issues with pod security policy
* Add examples using a non-root port-forwarding docker image
* Clarify how to find the database credentials
* Describe how to delete the port-forwarding pod, when finished
View the updated README [here](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/tree/update-external-access) (scroll down to 'Access outside the cluster')
fixes #21
=> Update external database access instructions

README.md, example/rds.tf, main.tf, variables.tf
This PR went through 2 complete rework.
- it introduced the `rds_family` variable
- `rds_family` is used by the `aws_db_parameter_group` resource
- Users are now expected to choose a family when invoking the module
- Readme Updated
=> Fix rds family

README.md
If users create port-forwarding pods using the instructions in
the README.md file, the pods they create will not be recreated if
the cluster moves the workload to a different node.
This change adds a note to that effect, with a link to the
kubernetes documentation about deployments.
=> Port-forwarding: Add note re. pods vs. deployments

README.md
Nobody should be doing this, since live-0 is deprecated.
=> Remove the note about deploying to live-0

main.tf, output.tf, variables.tf, versions.tf
Upgraded RDS module to TF 0.12. It was required to remove the extra brackets for all data resources required to pull the internal-subnets (it is an output which already comes as a list) as TF upgrade specify:
```
#
```
It was also required to set _db_iops_ variable to `type = number` in order to get working the conditional set in line 102: `storage_type = var.db_iops == 0 ? "gp2" : "io1"`
Code tested against our AWS account with the following values:
```
var.cluster_name
Enter a value: live-1
var.cluster_state_bucket
Enter a value: cloud-platform-terraform-state
```
=> Terraform 0.12 upgrade

main.tf, variables.tf
Related to: https://github.com/ministryofjustice/cloud-platform/issues/1560
What: To allow creating different DB family other than postgres. Currently the parameters for aws_db_parameter_group are hard coded to support postgres(eg. force_ssl). This creates a issue if user wants to create different DB family where the parameters are different. 
This PR will allow creating DB family where parameters can be passed as variable. The default values are
`  default = [
{
name         = "rds.force_ssl"
value        = "true"
apply_method = "immediate"
}`  
To apply this PR as a release,
1. Users who used `force_ssl = true` has to remove the line and hence the default values are being picked up
2. Users who use `force_ssl = "false"` has to replace the line with 
`  db_parameter = [
{
name         = …
=> Make db_parameter as variable to allow creation of different DB family

main.tf
Updated RDS module to use resource "random_password" instead of resource "random_string" to generate the db password.
This will fix pipeline exposing the db password.
Will raise a separate PR after releasing a new version updating readme and example.
=> Updated RDS module to use resource "random_password"

README.md
We had one service where the developer had copied the DB credentials from the kubernetes secret to a configMap, and so their application broke when the database password was rotated by terraform.
closes https://github.com/ministryofjustice/cloud-platform/issues/1753
=> Add note about not copying DB credentials

README.md
All RDS instances in the cloud platform are already using module version 5.3, as will any new instances created from now on. So, this warning is no longer required.
=> Remove upgrade warning from README

README.md, example/README.md, example/rds.tf, main.tf, variables.tf
Introduce optional `rds_name` variable.
If not provided, the module will generate a random identifier for the RDS.
=> Add custom RDS naming

README.md, example/rds.tf, main.tf, output.tf, variables.tf
Related to: https://github.com/ministryofjustice/cloud-platform/issues/1859
Variable db_identifier and skip_final_snapshot can now be changed when using this module
Creating read replica db instance doesnot require several variables to be passed when creating RDS instance such as aws_kms_key, db_subnet_group, DB username and DB password.
For read replica, final_snapshot_identifier has to be null as there are no snapshots created for read replica.
Variable skip_final_snapshot has to be set to true for read replica. For normal RDS instance, it is set to false(default)
ca_cert_identifier is not set explicitly as this causes read replica to reboot and not-ready state. Related to: https://github.com/terraform-providers/terraform-provider-aws/issues/11905
All the users of this module have set …
=> Adding replicate_source_db variable to support read_replica 

template/rds.tmpl
We no longer need to interpolate anything into this template. All values
are expected to come from a `variables.tf` file in the user's
namespace/resources folder, and the module name is hard-coded as "rds"
in the cli tool. So we can just hard-code it here instead, and let the
cli tool do a simple read and write to save whatever is in this file as
`resources/rds.tf`
=> Simplify the rds template file

template/rds.tmpl
Underscores are not allowed here, so 
`rds-instance_output` causes terraform plan to 
fail.
=> Fix configmap name

example/rds.tf, main.tf, template/rds.tmpl, variables.tf
This is to support the AWS cost reporter, so that we can breakdown AWS resource costs per namespace.
Add a "namespace" tag with a value of `var.namespace` to all AWS resources created via this module.
Also, remove the default "mojdigital" value for the `business-unit` tag - that's not a valid value, and we should be requiring users to supply the correct value anyway.
=> Add namespace tag

main.tf, output.tf
When we use performance Insights we need to reference the database by its resource ID instead of identifier. As it shows 
```
$ aws pi get-resource-metrics --service-type RDS --identifier cloud-platform-bfcf59724ea63960 --start-time `expr \`date +%s\` - 600 ` --end-time `expr \`date +%s\` - 300 ` --metric-queries '[{"Metric": "db.Transactions.xact_commit.avg" }]'
```
Unfortunately, it doesn't work if you use the RDS identifier, only works with the resource ID. So users need to be able to get resource ID as an output of the terraform module.
=> Added resource ID in order to use/query Performance Insights metrics

main.tf
There is not such action like that: it is a policy
=> Deleted action `AmazonRDSReadOnlyAccess`

main.tf
This change gives the IAM user created with the RDS instance additional
permissions, to enable users to upgrade their own RDS instances with
minimal involvement from the CP team.
The upgrade process is:
* Change RDS instance to use the defeault parameter group for it's
db_engine
* Tell the pipeline to upgrade the RDS instance via a normal env. repo.
PR
`rds:ModifyDBInstance` permission is required to change the instance's
DBParameterGroup.
Permissions on
`arn:aws:rds:${data.aws_region.current.name}:pg:default.*` are required
so that we can add the RDS instance to the parameter group's list of RDS
instance members.
Permissions on `aws_db_parameter_group.custom_parameters.arn` are
required to allow the IAM user to switch the RDS instance **back** to
the original parameter group (they …
=> Add "modify instance" permissions

README.md, example/rds.tf, main.tf, template/rds.tmpl, variables.tf
Add a db_max_allocated_storage terraform variable which defaults to 10TB, and gets passed through to the AWS instance definition as max_allocated_storage.
Once this PR is merged, create a 5.12 release.
This is the maximum up to which the RDS instance will be allowed to scale its storage amount. Setting this value has the effect of enabling storage autoscaling on the RDS instance.
I've carried out 2 tests on this module:
1. Create an RDS with this module version - RDS instance is created with storage autoscaling enabled (as shown in the configuration tab of the AWS console page for the RDS instance)
2. Create an RDS instance with the current version (5.10) of the module, insert some data and then change the module version to this version and terraform apply while accessing the database via …
=> Add storage autoscaling

template/rds.tmpl
When we create an environment using the CLI tool, the variable
`infrastructure_support` is defined in `variables.tf`
This change corrects the template to use the correct variable name.
Prior to this, the following sequence of commands will not work:
```
cloud-platform environment create
cloud-platform environment rds create
```
...because the pipeline will throw this error:
```
Error: Reference to undeclared input variable
on rds.tf line 18, in module "rds":
18:   infrastructure-support = var.infrastructure-support
An input variable with the name "infrastructure-support" has not been
declared. Did you mean "infrastructure_support"?
```
=> Correct var. to `infrastructure_support`

README.md, example/rds.tf, main.tf, variables.tf
In order to remove the interdependence between states (environment and infrastructure), with this change we are using data resources to query AWS API and get the metadata (VPC and subnets IDs)
Tested against cccd-dev's RDS instance:
```
No changes. Infrastructure is up-to-date.
This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```
as expected, no changes. Metadata is being pulled from AWS instead of terraform state.
=> Using AWS data resources instead of remote state

README.md
Reflects changes in https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#kubectl
This means the previous snippet errors out:
```
$ kubectl run --generator=run-pod/v1 shell --rm -i --tty --image bitnami/postgresql -- bash
Error: unknown flag: --generator
See 'kubectl run --help' for usage.
```
I was unsure to replace the section or provide a before/after syntax -- happy to amend if shorter is more preferred
=> Provide alternative syntax for 1.18+ kubectl

README.md, main.tf, variables.tf
This allows users to control and configure an option group and associate
this with the database.
One use case for this is enabling native backup and restore in RDS SQL
Server (ref: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.SQLServer.Options.BackupRestore.html)
- this can only be done via an option group...
(and we - the ppud-replacement team - need to do just that)
=> Allow a database instance to be associated to an option group

README.md, main.tf, variables.tf
We'd like to make our maintenance window more explicit so it matches the time when we have the least number of users of our tool. This change allows the window to be set in much the same way that the `backup_window` attribute can be set.
See [Adjusting the preferred DB instance maintenance window](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.Maintenance.html#AdjustingTheMaintenanceWindow) for more information about RDS maintenance windows.
=> Allow maintenance window to be configured

example/rds-mysql.tf, example/rds-postgresql.tf
This is to use "db.t3.small" as t2.small can only be used for Lower than PostgreSQL 13
=> Update the RDS template db_instance_class

example/rds-mssql.tf, example/rds-mysql.tf, variables.tf
Set the db_parameter default to "immediate"
This is because our default db_engine is Postgres , and Postgres doesn't need reboot:
when you set rds.force_ssl to 1, you don't need to reboot your DB instance.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/PostgreSQL.Concepts.General.SSL.html
For SQL:
The rds.force_ssl parameter is static, so after you change the value, you must reboot your DB instance for the change to take effect.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/SQLServer.Concepts.General.SSL.Using.html
=> Set the db_parameter default to "immediate"

example/rds-mssql.tf, example/rds-mysql.tf, example/rds-postgresql.tf
This PR updates the `examples` files to use:
- the latest module version
- updated supported database versions
- t4g instance types where appropriate
=> Update module version, database versions, and instance classes in examples

example/rds-mssql.tf, example/rds-mysql.tf, example/rds-postgresql.tf, main.tf, variables.tf
Enable auto start and stop of the RDS instances for cost saving
Ref:
https://github.com/ministryofjustice/cloud-platform-terraform-aws-scheduler/pull/1
=> enable_auto_start_stop

example/rds-mssql.tf, example/rds-mysql.tf, example/rds-postgresql.tf
The CLI uses these files to generate the rds module. The latest changes of vpc_name needs 5.16.12 and hence the pipeline fails if the rds module is generated from CLI
=> Update module version in examples

main.tf
This enables users to query supported db engine versions against given instance class
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/1266/commits/eb07468951637b0b68d4b61d7a943a4f4c8d6894
=> feat: add permissions for orderable DB instance options

README.md
It looks like in the past, the single example was expanded to separate examples for MySQL, MSSQL and Postgres but the README.md wasn't updated. This PR remedies that. 
There are no functional changes in this PR.
=> 📝  fix broken link to example config in README.md.

README.md, main.tf, variables.tf
This PR adds a new variable, `prepare_for_major_upgrade`, which when set to true, will change the parameter group to the default for their database; and turn on `allow_major_version_upgrade`.
=> Add a new variable to simplify parameter group resetting on major version upgrades

examples/rds-postgresql.tf
Fixes an error I got when using this file as a template: https://github.com/ministryofjustice/cloud-platform-environments/actions/runs/8817117259/job/24202735764?pr=22661
I guess this one was missed whenever the version was bumped
=> Fix version rds-postgresql.tf

README.md, variables.tf
This PR is to update the RDS instance default `rds-ca-2019` CA certificate which is expiring on **22/08/24** to to the new Amazon RDS cert `rds-ca-rsa2048-g1` which is valid for 40 year.
Relates to ministryofjustice/cloud-platform#5469
=> feat: Update ca cert identifier

main.tf
Relates to ministryofjustice/cloud-platform#6068
This PR updates our RDS module to reflect changes that were made to the AWS provider in `4.63` concerning re-enabling engine version setting for read replicas:
https://github.com/hashicorp/terraform-provider-aws/issues/24887
This is necessary for CP users who are manually (not auto minor upgrading) their RDS configurations where they have a primary and a replica.
In this case the user _must_ be able to set the minor version for their replica and carry out this prior to completing the minor version upgrade of their primary RDS.
=> chore: 🤖 fix conditional check for replica db name and engine version

README.md
`--generator=run-pod/v1` flag is deprecated in newer versions of kubectl.
=> update readme to remove deprecated flag
