ministryofjustice/cloud-platform-terraform-rds-instance

example/main.tf
example/output.tf
main.tf
output.tf
variables.tf

connects to closed ticket ministryofjustice/cloud-platform#303
**WHAT**
- Terraform format all tf files
**WHY**
Best practice

Terraform formatting

---

.circleci/config.yml

add .circleci/config.yml, configuring circle ci to run tf fmt and validate.

added circleci config, copied from cloud-platform-infra

---

README.md

* Change the docker image to `ministryofjustice/port-forward`
* Update the text

Update instructions wrt. non-root port-forwarding

---

README.md

Change can be viewed [here](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/tree/update-readme#access-outside-the-cluster)

Clarify the DB hostname for the port-forward pod

---

README.md
example/rds.tf
main.tf
variables.tf

This change is to  use `allow_major_version_upgrade` which Indicates that major version upgrades are allowed.

Updated the module to allow major version upgrade

---

README.md
example/rds.tf
main.tf
variables.tf

This is related to https://github.com/ministryofjustice/cloud-platform/issues/1197

Set force_ssl, default to "true"

---

README.md

Update the instructions to users for accessing their RDS database.

Tweak access instructions

---

example/main.tf
example/rds.tf
example/versions.tf
main.tf
output.tf
variables.tf
versions.tf

This is to upgrade RDS module to tf0.12.
Applied the changes from release TF12-DO_NOT-USE 
Applied "path" issue fixed in v4.8 by removing team_name

Upgrade RDS module to terraform 0.12

---

example/versions.tf

Updated terraform version in rds example

Updated terraform version in rds example

---

main.tf
variables.tf

Set by default to `false` with this variable can be enabled performance insight in RDS

New variable to enable performance insights

---

README.md
example/rds.tf

Added performance insight variable to the documentation (README) and also updated the example folder with this new variable (`performance_insights_enabled`)

Update docs and example folder

---

README.md
example/rds.tf

Added a note about RDS password rotation when updating to v5.3.

Update readme and example

---

main.tf
variables.tf

As this change will effect the existing RDS users, who use "force_ssl" and "pending-reboot"

Revert dynamic "parameter" changes

---

template/rds.tmpl

Related to work on building Cloud Platform CLI. 
The CLI rendered this template file to create rds instance.

Add template

---

README.md
example/rds.tf

- Add notes for adding inputs to Read replica if different than defaults.
- Add kubernetes_secret for read replica

Update example and note for Read replica 

---

template/rds.tmpl

Related to: https://github.com/ministryofjustice/cloud-platform/issues/1961

Convert template to fetch from variables template

---

README.md
example/README.md
example/rds.tf
template/rds.tmpl

Related to: https://github.com/ministryofjustice/cloud-platform/issues/2018

Add Configmap resource to RDS module

---

template/rds.tmpl

Related to
https://github.com/ministryofjustice/cloud-platform-environments/pull/2921

Use snake-case terraform variables

---

template/rds.tmpl

This is the file the CLI will use when users create RDS instances.

Update RDS template file

---

example/rds.tf
main.tf

This closes [this support ticket](https://github.com/ministryofjustice/cloud-platform/issues/2419)

Add Performance Insights API Access

---

README.md
example/rds.tf
main.tf
variables.tf

Add the backup_window and deletion_prevention flag to rds module

---

main.tf

Reverts ministryofjustice/cloud-platform-terraform-rds-instance#92

Revert "describe snapshots"

---

main.tf

Why: https://mojdt.slack.com/archives/C57UPMZLY/p1619445529245200

allow-DescribeDBEngineVersions

---

main.tf

This is related to a user request
https://github.com/ministryofjustice/cloud-platform/issues/2923

Enable stop and start of DB instances

---

main.tf

MS-SQL take longer than the default 40 mins

increase timeouts

---

main.tf

It is by using the guidelines as stated here:
https://github.com/hashicorp/terraform/issues/27282#issuecomment-745544614
Related to:
https://github.com/ministryofjustice/cloud-platform/issues/3111

Fix RDS changes result in a policy change

---

example/rds-mysql.tf

Not supported with mysql module. Passing tf plan but failing on apply

Comment out rds.force_sll param

---

README.md
example/rds-mssql.tf
example/rds-mysql.tf
example/rds-postgresql.tf
example/variables.tf
main.tf
test/unit-test/main.tf
variables.tf

This is to clear confusion around vpc_name vs cluster_name

Update RDS module

---

main.tf
variables.tf
versions.tf

Upgrade providers in RDS
Related to:
https://github.com/ministryofjustice/cloud-platform/issues/4234

Upgrade aws provider to version 4

---

example/rds-mssql.tf
example/rds-mysql.tf
example/rds-postgresql.tf

- fix(read_replica): bump read replica to the latest version
- fix(version): bump all examples to 5.16.15

Bump all examples to 5.16.15

---

examples/rds-mariadb.tf
examples/rds-mssql.tf
examples/rds-mysql.tf
examples/rds-postgresql.tf

Bump the example modules to the latest version

chore: Bump example files

---

examples/rds-mariadb.tf
examples/rds-mssql.tf
examples/rds-mysql.tf
examples/rds-postgresql.tf

relates to ministryofjustice/cloud-platform#6068

docs: ✏️ update examples for module update

---

README.md
main.tf

Add data block for new EKS specific subnet security group rules additions
Relates to relates to https://github.com/ministryofjustice/cloud-platform/issues/6030

Eks subnet sgs

---

examples/rds-mariadb.tf
examples/rds-mssql.tf
examples/rds-mysql.tf
examples/rds-postgresql.tf

- Update example module version

chore: update example module version

---

examples/rds-mariadb.tf
examples/rds-mssql.tf
examples/rds-mysql.tf
examples/rds-postgresql.tf

- Bump example module reference

chore: Bump RDS example module reference

---

.github/workflows/documentation.yml
.github/workflows/push-terraform-module-version.yaml
.github/workflows/unit.yml

Pin actions

---

README.md
main.tf
variables.tf

new migration feature branch to test changes on new rds module version, ahead of merging and cutting new no-ops release

chore: 🤖 setup refreshed migration changes branch for release
